version: 2

sources:
  - name: marts
    database: assignment-games-valve
    schema: valve_games

    tables:
      - name: mrt_games_price_history
        description: "A view that joins price history with information about games using application_id"
      - name: mrt_player_count_agg
        description: "A view that aggregates player count data per day and adds information about games"
      - name: mrt_top_popular_genres
      - name: mrt_top_popular_languages
      - name: mrt_game_popularity_summary